/* Generated by Yosys 0.55+8 (git sha1 9334a5c27, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "mac_unit" *)
(* src = "mac_unit.v:16.1-107.10" *)
module \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit (clk, rst, en, row_en, col_en, activation_in, weight_in, activation_out, weight_out, partial_sum_in, partial_sum_out);
  (* src = "mac_unit.v:101.55-101.80" *)
  wire [23:0] _00_;
  (* src = "mac_unit.v:44.21-44.32" *)
  wire _01_;
  wire _02_;
  (* src = "mac_unit.v:60.32-60.54" *)
  wire _03_;
  (* src = "mac_unit.v:60.34-60.53" *)
  wire _04_;
  wire [23:0] _05_;
  wire [23:0] _06_;
  (* src = "mac_unit.v:66.27-66.32" *)
  wire [7:0] a_iso;
  (* src = "mac_unit.v:58.10-58.18" *)
  wire act_zero;
  (* src = "mac_unit.v:30.40-30.53" *)
  input [7:0] activation_in;
  wire [7:0] activation_in;
  (* src = "mac_unit.v:32.40-32.54" *)
  output [7:0] activation_out;
  reg [7:0] activation_out;
  (* src = "mac_unit.v:21.40-21.43" *)
  input clk;
  wire clk;
  (* src = "mac_unit.v:27.40-27.46" *)
  input col_en;
  wire col_en;
  (* src = "mac_unit.v:60.10-60.16" *)
  wire do_mac;
  (* src = "mac_unit.v:25.40-25.42" *)
  input en;
  wire en;
  (* src = "mac_unit.v:44.10-44.18" *)
  wire local_en;
  (* src = "mac_unit.v:36.40-36.54" *)
  input [23:0] partial_sum_in;
  wire [23:0] partial_sum_in;
  (* src = "mac_unit.v:37.40-37.55" *)
  output [23:0] partial_sum_out;
  reg [23:0] partial_sum_out;
  (* src = "mac_unit.v:71.31-71.42" *)
  wire [15:0] prod_narrow;
  (* src = "mac_unit.v:26.40-26.46" *)
  input row_en;
  wire row_en;
  (* src = "mac_unit.v:22.40-22.43" *)
  input rst;
  wire rst;
  (* src = "mac_unit.v:67.27-67.32" *)
  wire [7:0] w_iso;
  (* src = "mac_unit.v:31.40-31.49" *)
  input [7:0] weight_in;
  wire [7:0] weight_in;
  (* src = "mac_unit.v:33.40-33.50" *)
  output [7:0] weight_out;
  reg [7:0] weight_out;
  (* src = "mac_unit.v:59.10-59.18" *)
  wire wgt_zero;
  assign _00_ = $signed(partial_sum_in) + (* src = "mac_unit.v:101.55-101.80" *) $signed({ prod_narrow[15], prod_narrow[15], prod_narrow[15], prod_narrow[15], prod_narrow[15], prod_narrow[15], prod_narrow[15], prod_narrow[15], prod_narrow });
  assign _01_ = en & (* src = "mac_unit.v:44.21-44.32" *) row_en;
  assign local_en = _01_ & (* src = "mac_unit.v:44.21-44.41" *) col_en;
  assign do_mac = local_en & (* src = "mac_unit.v:60.21-60.54" *) _03_;
  (* src = "mac_unit.v:82.5-105.8" *)
  always @(posedge clk)
    if (rst) activation_out <= 8'h00;
    else if (local_en) activation_out <= activation_in;
  (* src = "mac_unit.v:82.5-105.8" *)
  always @(posedge clk)
    if (rst) weight_out <= 8'h00;
    else if (local_en) weight_out <= weight_in;
  (* src = "mac_unit.v:82.5-105.8" *)
  always @(posedge clk)
    if (rst) partial_sum_out <= 24'h000000;
    else if (_02_) partial_sum_out <= _06_;
  assign _02_ = | { do_mac, local_en };
  assign act_zero = ! (* src = "mac_unit.v:58.22-58.44" *) activation_out;
  assign wgt_zero = ! (* src = "mac_unit.v:59.22-59.44" *) weight_out;
  assign prod_narrow = $signed(a_iso) * (* src = "mac_unit.v:71.45-71.58" *) $signed(w_iso);
  assign _03_ = ~ (* src = "mac_unit.v:60.32-60.54" *) _04_;
  assign _04_ = act_zero | (* src = "mac_unit.v:60.34-60.53" *) wgt_zero;
  assign _05_ = local_en ? (* src = "mac_unit.v:102.22-102.30|mac_unit.v:102.18-102.70" *) partial_sum_in : 24'hxxxxxx;
  assign _06_ = do_mac ? (* full_case = 32'd1 *) (* src = "mac_unit.v:101.17-101.23|mac_unit.v:101.13-102.70" *) _00_ : _05_;
  assign a_iso = local_en ? (* src = "mac_unit.v:66.35-66.67" *) activation_out : 8'h00;
  assign w_iso = local_en ? (* src = "mac_unit.v:67.35-67.67" *) weight_out : 8'h00;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "systolic_array.v:25.1-100.10" *)
module systolic_array(clk, rst, en, row_en, col_en, activation_in_flat, weight_in_flat, result_flat);
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[0].ROW[0].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[0].ROW[0].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[0].ROW[0].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[0].ROW[1].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[0].ROW[1].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[0].ROW[1].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[0].ROW[2].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[0].ROW[2].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[0].ROW[2].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[0].ROW[3].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[0].ROW[3].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[0].ROW[3].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[0].ROW[4].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[0].ROW[4].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[0].ROW[4].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[0].ROW[5].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[0].ROW[5].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[0].ROW[5].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[0].ROW[6].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[0].ROW[6].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[0].ROW[6].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[0].ROW[7].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[0].ROW[7].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[0].ROW[7].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[1].ROW[0].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[1].ROW[0].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[1].ROW[0].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[1].ROW[1].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[1].ROW[1].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[1].ROW[1].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[1].ROW[2].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[1].ROW[2].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[1].ROW[2].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[1].ROW[3].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[1].ROW[3].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[1].ROW[3].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[1].ROW[4].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[1].ROW[4].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[1].ROW[4].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[1].ROW[5].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[1].ROW[5].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[1].ROW[5].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[1].ROW[6].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[1].ROW[6].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[1].ROW[6].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[1].ROW[7].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[1].ROW[7].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[1].ROW[7].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[2].ROW[0].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[2].ROW[0].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[2].ROW[0].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[2].ROW[1].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[2].ROW[1].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[2].ROW[1].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[2].ROW[2].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[2].ROW[2].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[2].ROW[2].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[2].ROW[3].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[2].ROW[3].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[2].ROW[3].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[2].ROW[4].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[2].ROW[4].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[2].ROW[4].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[2].ROW[5].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[2].ROW[5].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[2].ROW[5].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[2].ROW[6].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[2].ROW[6].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[2].ROW[6].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[2].ROW[7].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[2].ROW[7].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[2].ROW[7].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[3].ROW[0].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[3].ROW[0].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[3].ROW[0].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[3].ROW[1].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[3].ROW[1].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[3].ROW[1].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[3].ROW[2].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[3].ROW[2].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[3].ROW[2].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[3].ROW[3].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[3].ROW[3].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[3].ROW[3].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[3].ROW[4].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[3].ROW[4].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[3].ROW[4].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[3].ROW[5].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[3].ROW[5].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[3].ROW[5].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[3].ROW[6].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[3].ROW[6].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[3].ROW[6].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[3].ROW[7].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[3].ROW[7].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[3].ROW[7].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[4].ROW[0].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[4].ROW[0].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[4].ROW[0].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[4].ROW[1].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[4].ROW[1].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[4].ROW[1].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[4].ROW[2].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[4].ROW[2].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[4].ROW[2].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[4].ROW[3].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[4].ROW[3].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[4].ROW[3].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[4].ROW[4].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[4].ROW[4].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[4].ROW[4].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[4].ROW[5].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[4].ROW[5].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[4].ROW[5].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[4].ROW[6].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[4].ROW[6].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[4].ROW[6].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[4].ROW[7].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[4].ROW[7].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[4].ROW[7].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[5].ROW[0].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[5].ROW[0].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[5].ROW[0].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[5].ROW[1].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[5].ROW[1].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[5].ROW[1].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[5].ROW[2].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[5].ROW[2].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[5].ROW[2].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[5].ROW[3].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[5].ROW[3].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[5].ROW[3].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[5].ROW[4].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[5].ROW[4].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[5].ROW[4].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[5].ROW[5].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[5].ROW[5].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[5].ROW[5].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[5].ROW[6].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[5].ROW[6].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[5].ROW[6].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[5].ROW[7].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[5].ROW[7].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[5].ROW[7].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[6].ROW[0].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[6].ROW[0].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[6].ROW[0].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[6].ROW[1].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[6].ROW[1].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[6].ROW[1].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[6].ROW[2].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[6].ROW[2].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[6].ROW[2].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[6].ROW[3].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[6].ROW[3].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[6].ROW[3].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[6].ROW[4].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[6].ROW[4].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[6].ROW[4].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[6].ROW[5].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[6].ROW[5].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[6].ROW[5].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[6].ROW[6].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[6].ROW[6].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[6].ROW[6].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  wire [7:0] \COL[6].ROW[7].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[6].ROW[7].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[6].ROW[7].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[7].ROW[0].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[7].ROW[0].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[7].ROW[0].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[7].ROW[1].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[7].ROW[1].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[7].ROW[1].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[7].ROW[2].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[7].ROW[2].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[7].ROW[2].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[7].ROW[3].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[7].ROW[3].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[7].ROW[3].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[7].ROW[4].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[7].ROW[4].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[7].ROW[4].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[7].ROW[5].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[7].ROW[5].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[7].ROW[5].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[7].ROW[6].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[7].ROW[6].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  wire [7:0] \COL[7].ROW[6].wgt_out ;
  (* src = "systolic_array.v:66.31-66.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[7].ROW[7].act_out ;
  (* src = "systolic_array.v:69.34-69.42" *)
  wire [23:0] \COL[7].ROW[7].psum_out ;
  (* src = "systolic_array.v:67.31-67.38" *)
  (* unused_bits = "0 1 2 3 4 5 6 7" *)
  wire [7:0] \COL[7].ROW[7].wgt_out ;
  (* src = "systolic_array.v:36.31-36.49" *)
  input [63:0] activation_in_flat;
  wire [63:0] activation_in_flat;
  (* src = "systolic_array.v:31.31-31.34" *)
  input clk;
  wire clk;
  (* src = "systolic_array.v:35.31-35.37" *)
  input [7:0] col_en;
  wire [7:0] col_en;
  (* src = "systolic_array.v:33.31-33.33" *)
  input en;
  wire en;
  (* src = "systolic_array.v:38.32-38.43" *)
  output [1535:0] result_flat;
  wire [1535:0] result_flat;
  (* src = "systolic_array.v:34.31-34.37" *)
  input [7:0] row_en;
  wire [7:0] row_en;
  (* src = "systolic_array.v:32.31-32.34" *)
  input rst;
  wire rst;
  (* src = "systolic_array.v:37.31-37.45" *)
  input [63:0] weight_in_flat;
  wire [63:0] weight_in_flat;
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[0].ROW[0].PE  (
    .activation_in(activation_in_flat[7:0]),
    .activation_out(\COL[0].ROW[0].act_out ),
    .clk(clk),
    .col_en(col_en[0]),
    .en(en),
    .partial_sum_in(24'h000000),
    .partial_sum_out(\COL[0].ROW[0].psum_out ),
    .row_en(row_en[0]),
    .rst(rst),
    .weight_in(weight_in_flat[7:0]),
    .weight_out(\COL[0].ROW[0].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[0].ROW[1].PE  (
    .activation_in(activation_in_flat[15:8]),
    .activation_out(\COL[0].ROW[1].act_out ),
    .clk(clk),
    .col_en(col_en[0]),
    .en(en),
    .partial_sum_in(24'h000000),
    .partial_sum_out(\COL[0].ROW[1].psum_out ),
    .row_en(row_en[1]),
    .rst(rst),
    .weight_in(\COL[0].ROW[0].wgt_out ),
    .weight_out(\COL[0].ROW[1].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[0].ROW[2].PE  (
    .activation_in(activation_in_flat[23:16]),
    .activation_out(\COL[0].ROW[2].act_out ),
    .clk(clk),
    .col_en(col_en[0]),
    .en(en),
    .partial_sum_in(24'h000000),
    .partial_sum_out(\COL[0].ROW[2].psum_out ),
    .row_en(row_en[2]),
    .rst(rst),
    .weight_in(\COL[0].ROW[1].wgt_out ),
    .weight_out(\COL[0].ROW[2].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[0].ROW[3].PE  (
    .activation_in(activation_in_flat[31:24]),
    .activation_out(\COL[0].ROW[3].act_out ),
    .clk(clk),
    .col_en(col_en[0]),
    .en(en),
    .partial_sum_in(24'h000000),
    .partial_sum_out(\COL[0].ROW[3].psum_out ),
    .row_en(row_en[3]),
    .rst(rst),
    .weight_in(\COL[0].ROW[2].wgt_out ),
    .weight_out(\COL[0].ROW[3].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[0].ROW[4].PE  (
    .activation_in(activation_in_flat[39:32]),
    .activation_out(\COL[0].ROW[4].act_out ),
    .clk(clk),
    .col_en(col_en[0]),
    .en(en),
    .partial_sum_in(24'h000000),
    .partial_sum_out(\COL[0].ROW[4].psum_out ),
    .row_en(row_en[4]),
    .rst(rst),
    .weight_in(\COL[0].ROW[3].wgt_out ),
    .weight_out(\COL[0].ROW[4].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[0].ROW[5].PE  (
    .activation_in(activation_in_flat[47:40]),
    .activation_out(\COL[0].ROW[5].act_out ),
    .clk(clk),
    .col_en(col_en[0]),
    .en(en),
    .partial_sum_in(24'h000000),
    .partial_sum_out(\COL[0].ROW[5].psum_out ),
    .row_en(row_en[5]),
    .rst(rst),
    .weight_in(\COL[0].ROW[4].wgt_out ),
    .weight_out(\COL[0].ROW[5].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[0].ROW[6].PE  (
    .activation_in(activation_in_flat[55:48]),
    .activation_out(\COL[0].ROW[6].act_out ),
    .clk(clk),
    .col_en(col_en[0]),
    .en(en),
    .partial_sum_in(24'h000000),
    .partial_sum_out(\COL[0].ROW[6].psum_out ),
    .row_en(row_en[6]),
    .rst(rst),
    .weight_in(\COL[0].ROW[5].wgt_out ),
    .weight_out(\COL[0].ROW[6].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[0].ROW[7].PE  (
    .activation_in(activation_in_flat[63:56]),
    .activation_out(\COL[0].ROW[7].act_out ),
    .clk(clk),
    .col_en(col_en[0]),
    .en(en),
    .partial_sum_in(24'h000000),
    .partial_sum_out(\COL[0].ROW[7].psum_out ),
    .row_en(row_en[7]),
    .rst(rst),
    .weight_in(\COL[0].ROW[6].wgt_out ),
    .weight_out(\COL[0].ROW[7].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[1].ROW[0].PE  (
    .activation_in(\COL[0].ROW[0].act_out ),
    .activation_out(\COL[1].ROW[0].act_out ),
    .clk(clk),
    .col_en(col_en[1]),
    .en(en),
    .partial_sum_in(\COL[0].ROW[0].psum_out ),
    .partial_sum_out(\COL[1].ROW[0].psum_out ),
    .row_en(row_en[0]),
    .rst(rst),
    .weight_in(weight_in_flat[15:8]),
    .weight_out(\COL[1].ROW[0].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[1].ROW[1].PE  (
    .activation_in(\COL[0].ROW[1].act_out ),
    .activation_out(\COL[1].ROW[1].act_out ),
    .clk(clk),
    .col_en(col_en[1]),
    .en(en),
    .partial_sum_in(\COL[0].ROW[1].psum_out ),
    .partial_sum_out(\COL[1].ROW[1].psum_out ),
    .row_en(row_en[1]),
    .rst(rst),
    .weight_in(\COL[1].ROW[0].wgt_out ),
    .weight_out(\COL[1].ROW[1].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[1].ROW[2].PE  (
    .activation_in(\COL[0].ROW[2].act_out ),
    .activation_out(\COL[1].ROW[2].act_out ),
    .clk(clk),
    .col_en(col_en[1]),
    .en(en),
    .partial_sum_in(\COL[0].ROW[2].psum_out ),
    .partial_sum_out(\COL[1].ROW[2].psum_out ),
    .row_en(row_en[2]),
    .rst(rst),
    .weight_in(\COL[1].ROW[1].wgt_out ),
    .weight_out(\COL[1].ROW[2].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[1].ROW[3].PE  (
    .activation_in(\COL[0].ROW[3].act_out ),
    .activation_out(\COL[1].ROW[3].act_out ),
    .clk(clk),
    .col_en(col_en[1]),
    .en(en),
    .partial_sum_in(\COL[0].ROW[3].psum_out ),
    .partial_sum_out(\COL[1].ROW[3].psum_out ),
    .row_en(row_en[3]),
    .rst(rst),
    .weight_in(\COL[1].ROW[2].wgt_out ),
    .weight_out(\COL[1].ROW[3].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[1].ROW[4].PE  (
    .activation_in(\COL[0].ROW[4].act_out ),
    .activation_out(\COL[1].ROW[4].act_out ),
    .clk(clk),
    .col_en(col_en[1]),
    .en(en),
    .partial_sum_in(\COL[0].ROW[4].psum_out ),
    .partial_sum_out(\COL[1].ROW[4].psum_out ),
    .row_en(row_en[4]),
    .rst(rst),
    .weight_in(\COL[1].ROW[3].wgt_out ),
    .weight_out(\COL[1].ROW[4].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[1].ROW[5].PE  (
    .activation_in(\COL[0].ROW[5].act_out ),
    .activation_out(\COL[1].ROW[5].act_out ),
    .clk(clk),
    .col_en(col_en[1]),
    .en(en),
    .partial_sum_in(\COL[0].ROW[5].psum_out ),
    .partial_sum_out(\COL[1].ROW[5].psum_out ),
    .row_en(row_en[5]),
    .rst(rst),
    .weight_in(\COL[1].ROW[4].wgt_out ),
    .weight_out(\COL[1].ROW[5].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[1].ROW[6].PE  (
    .activation_in(\COL[0].ROW[6].act_out ),
    .activation_out(\COL[1].ROW[6].act_out ),
    .clk(clk),
    .col_en(col_en[1]),
    .en(en),
    .partial_sum_in(\COL[0].ROW[6].psum_out ),
    .partial_sum_out(\COL[1].ROW[6].psum_out ),
    .row_en(row_en[6]),
    .rst(rst),
    .weight_in(\COL[1].ROW[5].wgt_out ),
    .weight_out(\COL[1].ROW[6].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[1].ROW[7].PE  (
    .activation_in(\COL[0].ROW[7].act_out ),
    .activation_out(\COL[1].ROW[7].act_out ),
    .clk(clk),
    .col_en(col_en[1]),
    .en(en),
    .partial_sum_in(\COL[0].ROW[7].psum_out ),
    .partial_sum_out(\COL[1].ROW[7].psum_out ),
    .row_en(row_en[7]),
    .rst(rst),
    .weight_in(\COL[1].ROW[6].wgt_out ),
    .weight_out(\COL[1].ROW[7].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[2].ROW[0].PE  (
    .activation_in(\COL[1].ROW[0].act_out ),
    .activation_out(\COL[2].ROW[0].act_out ),
    .clk(clk),
    .col_en(col_en[2]),
    .en(en),
    .partial_sum_in(\COL[1].ROW[0].psum_out ),
    .partial_sum_out(\COL[2].ROW[0].psum_out ),
    .row_en(row_en[0]),
    .rst(rst),
    .weight_in(weight_in_flat[23:16]),
    .weight_out(\COL[2].ROW[0].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[2].ROW[1].PE  (
    .activation_in(\COL[1].ROW[1].act_out ),
    .activation_out(\COL[2].ROW[1].act_out ),
    .clk(clk),
    .col_en(col_en[2]),
    .en(en),
    .partial_sum_in(\COL[1].ROW[1].psum_out ),
    .partial_sum_out(\COL[2].ROW[1].psum_out ),
    .row_en(row_en[1]),
    .rst(rst),
    .weight_in(\COL[2].ROW[0].wgt_out ),
    .weight_out(\COL[2].ROW[1].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[2].ROW[2].PE  (
    .activation_in(\COL[1].ROW[2].act_out ),
    .activation_out(\COL[2].ROW[2].act_out ),
    .clk(clk),
    .col_en(col_en[2]),
    .en(en),
    .partial_sum_in(\COL[1].ROW[2].psum_out ),
    .partial_sum_out(\COL[2].ROW[2].psum_out ),
    .row_en(row_en[2]),
    .rst(rst),
    .weight_in(\COL[2].ROW[1].wgt_out ),
    .weight_out(\COL[2].ROW[2].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[2].ROW[3].PE  (
    .activation_in(\COL[1].ROW[3].act_out ),
    .activation_out(\COL[2].ROW[3].act_out ),
    .clk(clk),
    .col_en(col_en[2]),
    .en(en),
    .partial_sum_in(\COL[1].ROW[3].psum_out ),
    .partial_sum_out(\COL[2].ROW[3].psum_out ),
    .row_en(row_en[3]),
    .rst(rst),
    .weight_in(\COL[2].ROW[2].wgt_out ),
    .weight_out(\COL[2].ROW[3].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[2].ROW[4].PE  (
    .activation_in(\COL[1].ROW[4].act_out ),
    .activation_out(\COL[2].ROW[4].act_out ),
    .clk(clk),
    .col_en(col_en[2]),
    .en(en),
    .partial_sum_in(\COL[1].ROW[4].psum_out ),
    .partial_sum_out(\COL[2].ROW[4].psum_out ),
    .row_en(row_en[4]),
    .rst(rst),
    .weight_in(\COL[2].ROW[3].wgt_out ),
    .weight_out(\COL[2].ROW[4].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[2].ROW[5].PE  (
    .activation_in(\COL[1].ROW[5].act_out ),
    .activation_out(\COL[2].ROW[5].act_out ),
    .clk(clk),
    .col_en(col_en[2]),
    .en(en),
    .partial_sum_in(\COL[1].ROW[5].psum_out ),
    .partial_sum_out(\COL[2].ROW[5].psum_out ),
    .row_en(row_en[5]),
    .rst(rst),
    .weight_in(\COL[2].ROW[4].wgt_out ),
    .weight_out(\COL[2].ROW[5].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[2].ROW[6].PE  (
    .activation_in(\COL[1].ROW[6].act_out ),
    .activation_out(\COL[2].ROW[6].act_out ),
    .clk(clk),
    .col_en(col_en[2]),
    .en(en),
    .partial_sum_in(\COL[1].ROW[6].psum_out ),
    .partial_sum_out(\COL[2].ROW[6].psum_out ),
    .row_en(row_en[6]),
    .rst(rst),
    .weight_in(\COL[2].ROW[5].wgt_out ),
    .weight_out(\COL[2].ROW[6].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[2].ROW[7].PE  (
    .activation_in(\COL[1].ROW[7].act_out ),
    .activation_out(\COL[2].ROW[7].act_out ),
    .clk(clk),
    .col_en(col_en[2]),
    .en(en),
    .partial_sum_in(\COL[1].ROW[7].psum_out ),
    .partial_sum_out(\COL[2].ROW[7].psum_out ),
    .row_en(row_en[7]),
    .rst(rst),
    .weight_in(\COL[2].ROW[6].wgt_out ),
    .weight_out(\COL[2].ROW[7].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[3].ROW[0].PE  (
    .activation_in(\COL[2].ROW[0].act_out ),
    .activation_out(\COL[3].ROW[0].act_out ),
    .clk(clk),
    .col_en(col_en[3]),
    .en(en),
    .partial_sum_in(\COL[2].ROW[0].psum_out ),
    .partial_sum_out(\COL[3].ROW[0].psum_out ),
    .row_en(row_en[0]),
    .rst(rst),
    .weight_in(weight_in_flat[31:24]),
    .weight_out(\COL[3].ROW[0].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[3].ROW[1].PE  (
    .activation_in(\COL[2].ROW[1].act_out ),
    .activation_out(\COL[3].ROW[1].act_out ),
    .clk(clk),
    .col_en(col_en[3]),
    .en(en),
    .partial_sum_in(\COL[2].ROW[1].psum_out ),
    .partial_sum_out(\COL[3].ROW[1].psum_out ),
    .row_en(row_en[1]),
    .rst(rst),
    .weight_in(\COL[3].ROW[0].wgt_out ),
    .weight_out(\COL[3].ROW[1].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[3].ROW[2].PE  (
    .activation_in(\COL[2].ROW[2].act_out ),
    .activation_out(\COL[3].ROW[2].act_out ),
    .clk(clk),
    .col_en(col_en[3]),
    .en(en),
    .partial_sum_in(\COL[2].ROW[2].psum_out ),
    .partial_sum_out(\COL[3].ROW[2].psum_out ),
    .row_en(row_en[2]),
    .rst(rst),
    .weight_in(\COL[3].ROW[1].wgt_out ),
    .weight_out(\COL[3].ROW[2].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[3].ROW[3].PE  (
    .activation_in(\COL[2].ROW[3].act_out ),
    .activation_out(\COL[3].ROW[3].act_out ),
    .clk(clk),
    .col_en(col_en[3]),
    .en(en),
    .partial_sum_in(\COL[2].ROW[3].psum_out ),
    .partial_sum_out(\COL[3].ROW[3].psum_out ),
    .row_en(row_en[3]),
    .rst(rst),
    .weight_in(\COL[3].ROW[2].wgt_out ),
    .weight_out(\COL[3].ROW[3].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[3].ROW[4].PE  (
    .activation_in(\COL[2].ROW[4].act_out ),
    .activation_out(\COL[3].ROW[4].act_out ),
    .clk(clk),
    .col_en(col_en[3]),
    .en(en),
    .partial_sum_in(\COL[2].ROW[4].psum_out ),
    .partial_sum_out(\COL[3].ROW[4].psum_out ),
    .row_en(row_en[4]),
    .rst(rst),
    .weight_in(\COL[3].ROW[3].wgt_out ),
    .weight_out(\COL[3].ROW[4].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[3].ROW[5].PE  (
    .activation_in(\COL[2].ROW[5].act_out ),
    .activation_out(\COL[3].ROW[5].act_out ),
    .clk(clk),
    .col_en(col_en[3]),
    .en(en),
    .partial_sum_in(\COL[2].ROW[5].psum_out ),
    .partial_sum_out(\COL[3].ROW[5].psum_out ),
    .row_en(row_en[5]),
    .rst(rst),
    .weight_in(\COL[3].ROW[4].wgt_out ),
    .weight_out(\COL[3].ROW[5].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[3].ROW[6].PE  (
    .activation_in(\COL[2].ROW[6].act_out ),
    .activation_out(\COL[3].ROW[6].act_out ),
    .clk(clk),
    .col_en(col_en[3]),
    .en(en),
    .partial_sum_in(\COL[2].ROW[6].psum_out ),
    .partial_sum_out(\COL[3].ROW[6].psum_out ),
    .row_en(row_en[6]),
    .rst(rst),
    .weight_in(\COL[3].ROW[5].wgt_out ),
    .weight_out(\COL[3].ROW[6].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[3].ROW[7].PE  (
    .activation_in(\COL[2].ROW[7].act_out ),
    .activation_out(\COL[3].ROW[7].act_out ),
    .clk(clk),
    .col_en(col_en[3]),
    .en(en),
    .partial_sum_in(\COL[2].ROW[7].psum_out ),
    .partial_sum_out(\COL[3].ROW[7].psum_out ),
    .row_en(row_en[7]),
    .rst(rst),
    .weight_in(\COL[3].ROW[6].wgt_out ),
    .weight_out(\COL[3].ROW[7].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[4].ROW[0].PE  (
    .activation_in(\COL[3].ROW[0].act_out ),
    .activation_out(\COL[4].ROW[0].act_out ),
    .clk(clk),
    .col_en(col_en[4]),
    .en(en),
    .partial_sum_in(\COL[3].ROW[0].psum_out ),
    .partial_sum_out(\COL[4].ROW[0].psum_out ),
    .row_en(row_en[0]),
    .rst(rst),
    .weight_in(weight_in_flat[39:32]),
    .weight_out(\COL[4].ROW[0].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[4].ROW[1].PE  (
    .activation_in(\COL[3].ROW[1].act_out ),
    .activation_out(\COL[4].ROW[1].act_out ),
    .clk(clk),
    .col_en(col_en[4]),
    .en(en),
    .partial_sum_in(\COL[3].ROW[1].psum_out ),
    .partial_sum_out(\COL[4].ROW[1].psum_out ),
    .row_en(row_en[1]),
    .rst(rst),
    .weight_in(\COL[4].ROW[0].wgt_out ),
    .weight_out(\COL[4].ROW[1].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[4].ROW[2].PE  (
    .activation_in(\COL[3].ROW[2].act_out ),
    .activation_out(\COL[4].ROW[2].act_out ),
    .clk(clk),
    .col_en(col_en[4]),
    .en(en),
    .partial_sum_in(\COL[3].ROW[2].psum_out ),
    .partial_sum_out(\COL[4].ROW[2].psum_out ),
    .row_en(row_en[2]),
    .rst(rst),
    .weight_in(\COL[4].ROW[1].wgt_out ),
    .weight_out(\COL[4].ROW[2].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[4].ROW[3].PE  (
    .activation_in(\COL[3].ROW[3].act_out ),
    .activation_out(\COL[4].ROW[3].act_out ),
    .clk(clk),
    .col_en(col_en[4]),
    .en(en),
    .partial_sum_in(\COL[3].ROW[3].psum_out ),
    .partial_sum_out(\COL[4].ROW[3].psum_out ),
    .row_en(row_en[3]),
    .rst(rst),
    .weight_in(\COL[4].ROW[2].wgt_out ),
    .weight_out(\COL[4].ROW[3].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[4].ROW[4].PE  (
    .activation_in(\COL[3].ROW[4].act_out ),
    .activation_out(\COL[4].ROW[4].act_out ),
    .clk(clk),
    .col_en(col_en[4]),
    .en(en),
    .partial_sum_in(\COL[3].ROW[4].psum_out ),
    .partial_sum_out(\COL[4].ROW[4].psum_out ),
    .row_en(row_en[4]),
    .rst(rst),
    .weight_in(\COL[4].ROW[3].wgt_out ),
    .weight_out(\COL[4].ROW[4].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[4].ROW[5].PE  (
    .activation_in(\COL[3].ROW[5].act_out ),
    .activation_out(\COL[4].ROW[5].act_out ),
    .clk(clk),
    .col_en(col_en[4]),
    .en(en),
    .partial_sum_in(\COL[3].ROW[5].psum_out ),
    .partial_sum_out(\COL[4].ROW[5].psum_out ),
    .row_en(row_en[5]),
    .rst(rst),
    .weight_in(\COL[4].ROW[4].wgt_out ),
    .weight_out(\COL[4].ROW[5].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[4].ROW[6].PE  (
    .activation_in(\COL[3].ROW[6].act_out ),
    .activation_out(\COL[4].ROW[6].act_out ),
    .clk(clk),
    .col_en(col_en[4]),
    .en(en),
    .partial_sum_in(\COL[3].ROW[6].psum_out ),
    .partial_sum_out(\COL[4].ROW[6].psum_out ),
    .row_en(row_en[6]),
    .rst(rst),
    .weight_in(\COL[4].ROW[5].wgt_out ),
    .weight_out(\COL[4].ROW[6].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[4].ROW[7].PE  (
    .activation_in(\COL[3].ROW[7].act_out ),
    .activation_out(\COL[4].ROW[7].act_out ),
    .clk(clk),
    .col_en(col_en[4]),
    .en(en),
    .partial_sum_in(\COL[3].ROW[7].psum_out ),
    .partial_sum_out(\COL[4].ROW[7].psum_out ),
    .row_en(row_en[7]),
    .rst(rst),
    .weight_in(\COL[4].ROW[6].wgt_out ),
    .weight_out(\COL[4].ROW[7].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[5].ROW[0].PE  (
    .activation_in(\COL[4].ROW[0].act_out ),
    .activation_out(\COL[5].ROW[0].act_out ),
    .clk(clk),
    .col_en(col_en[5]),
    .en(en),
    .partial_sum_in(\COL[4].ROW[0].psum_out ),
    .partial_sum_out(\COL[5].ROW[0].psum_out ),
    .row_en(row_en[0]),
    .rst(rst),
    .weight_in(weight_in_flat[47:40]),
    .weight_out(\COL[5].ROW[0].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[5].ROW[1].PE  (
    .activation_in(\COL[4].ROW[1].act_out ),
    .activation_out(\COL[5].ROW[1].act_out ),
    .clk(clk),
    .col_en(col_en[5]),
    .en(en),
    .partial_sum_in(\COL[4].ROW[1].psum_out ),
    .partial_sum_out(\COL[5].ROW[1].psum_out ),
    .row_en(row_en[1]),
    .rst(rst),
    .weight_in(\COL[5].ROW[0].wgt_out ),
    .weight_out(\COL[5].ROW[1].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[5].ROW[2].PE  (
    .activation_in(\COL[4].ROW[2].act_out ),
    .activation_out(\COL[5].ROW[2].act_out ),
    .clk(clk),
    .col_en(col_en[5]),
    .en(en),
    .partial_sum_in(\COL[4].ROW[2].psum_out ),
    .partial_sum_out(\COL[5].ROW[2].psum_out ),
    .row_en(row_en[2]),
    .rst(rst),
    .weight_in(\COL[5].ROW[1].wgt_out ),
    .weight_out(\COL[5].ROW[2].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[5].ROW[3].PE  (
    .activation_in(\COL[4].ROW[3].act_out ),
    .activation_out(\COL[5].ROW[3].act_out ),
    .clk(clk),
    .col_en(col_en[5]),
    .en(en),
    .partial_sum_in(\COL[4].ROW[3].psum_out ),
    .partial_sum_out(\COL[5].ROW[3].psum_out ),
    .row_en(row_en[3]),
    .rst(rst),
    .weight_in(\COL[5].ROW[2].wgt_out ),
    .weight_out(\COL[5].ROW[3].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[5].ROW[4].PE  (
    .activation_in(\COL[4].ROW[4].act_out ),
    .activation_out(\COL[5].ROW[4].act_out ),
    .clk(clk),
    .col_en(col_en[5]),
    .en(en),
    .partial_sum_in(\COL[4].ROW[4].psum_out ),
    .partial_sum_out(\COL[5].ROW[4].psum_out ),
    .row_en(row_en[4]),
    .rst(rst),
    .weight_in(\COL[5].ROW[3].wgt_out ),
    .weight_out(\COL[5].ROW[4].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[5].ROW[5].PE  (
    .activation_in(\COL[4].ROW[5].act_out ),
    .activation_out(\COL[5].ROW[5].act_out ),
    .clk(clk),
    .col_en(col_en[5]),
    .en(en),
    .partial_sum_in(\COL[4].ROW[5].psum_out ),
    .partial_sum_out(\COL[5].ROW[5].psum_out ),
    .row_en(row_en[5]),
    .rst(rst),
    .weight_in(\COL[5].ROW[4].wgt_out ),
    .weight_out(\COL[5].ROW[5].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[5].ROW[6].PE  (
    .activation_in(\COL[4].ROW[6].act_out ),
    .activation_out(\COL[5].ROW[6].act_out ),
    .clk(clk),
    .col_en(col_en[5]),
    .en(en),
    .partial_sum_in(\COL[4].ROW[6].psum_out ),
    .partial_sum_out(\COL[5].ROW[6].psum_out ),
    .row_en(row_en[6]),
    .rst(rst),
    .weight_in(\COL[5].ROW[5].wgt_out ),
    .weight_out(\COL[5].ROW[6].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[5].ROW[7].PE  (
    .activation_in(\COL[4].ROW[7].act_out ),
    .activation_out(\COL[5].ROW[7].act_out ),
    .clk(clk),
    .col_en(col_en[5]),
    .en(en),
    .partial_sum_in(\COL[4].ROW[7].psum_out ),
    .partial_sum_out(\COL[5].ROW[7].psum_out ),
    .row_en(row_en[7]),
    .rst(rst),
    .weight_in(\COL[5].ROW[6].wgt_out ),
    .weight_out(\COL[5].ROW[7].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[6].ROW[0].PE  (
    .activation_in(\COL[5].ROW[0].act_out ),
    .activation_out(\COL[6].ROW[0].act_out ),
    .clk(clk),
    .col_en(col_en[6]),
    .en(en),
    .partial_sum_in(\COL[5].ROW[0].psum_out ),
    .partial_sum_out(\COL[6].ROW[0].psum_out ),
    .row_en(row_en[0]),
    .rst(rst),
    .weight_in(weight_in_flat[55:48]),
    .weight_out(\COL[6].ROW[0].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[6].ROW[1].PE  (
    .activation_in(\COL[5].ROW[1].act_out ),
    .activation_out(\COL[6].ROW[1].act_out ),
    .clk(clk),
    .col_en(col_en[6]),
    .en(en),
    .partial_sum_in(\COL[5].ROW[1].psum_out ),
    .partial_sum_out(\COL[6].ROW[1].psum_out ),
    .row_en(row_en[1]),
    .rst(rst),
    .weight_in(\COL[6].ROW[0].wgt_out ),
    .weight_out(\COL[6].ROW[1].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[6].ROW[2].PE  (
    .activation_in(\COL[5].ROW[2].act_out ),
    .activation_out(\COL[6].ROW[2].act_out ),
    .clk(clk),
    .col_en(col_en[6]),
    .en(en),
    .partial_sum_in(\COL[5].ROW[2].psum_out ),
    .partial_sum_out(\COL[6].ROW[2].psum_out ),
    .row_en(row_en[2]),
    .rst(rst),
    .weight_in(\COL[6].ROW[1].wgt_out ),
    .weight_out(\COL[6].ROW[2].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[6].ROW[3].PE  (
    .activation_in(\COL[5].ROW[3].act_out ),
    .activation_out(\COL[6].ROW[3].act_out ),
    .clk(clk),
    .col_en(col_en[6]),
    .en(en),
    .partial_sum_in(\COL[5].ROW[3].psum_out ),
    .partial_sum_out(\COL[6].ROW[3].psum_out ),
    .row_en(row_en[3]),
    .rst(rst),
    .weight_in(\COL[6].ROW[2].wgt_out ),
    .weight_out(\COL[6].ROW[3].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[6].ROW[4].PE  (
    .activation_in(\COL[5].ROW[4].act_out ),
    .activation_out(\COL[6].ROW[4].act_out ),
    .clk(clk),
    .col_en(col_en[6]),
    .en(en),
    .partial_sum_in(\COL[5].ROW[4].psum_out ),
    .partial_sum_out(\COL[6].ROW[4].psum_out ),
    .row_en(row_en[4]),
    .rst(rst),
    .weight_in(\COL[6].ROW[3].wgt_out ),
    .weight_out(\COL[6].ROW[4].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[6].ROW[5].PE  (
    .activation_in(\COL[5].ROW[5].act_out ),
    .activation_out(\COL[6].ROW[5].act_out ),
    .clk(clk),
    .col_en(col_en[6]),
    .en(en),
    .partial_sum_in(\COL[5].ROW[5].psum_out ),
    .partial_sum_out(\COL[6].ROW[5].psum_out ),
    .row_en(row_en[5]),
    .rst(rst),
    .weight_in(\COL[6].ROW[4].wgt_out ),
    .weight_out(\COL[6].ROW[5].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[6].ROW[6].PE  (
    .activation_in(\COL[5].ROW[6].act_out ),
    .activation_out(\COL[6].ROW[6].act_out ),
    .clk(clk),
    .col_en(col_en[6]),
    .en(en),
    .partial_sum_in(\COL[5].ROW[6].psum_out ),
    .partial_sum_out(\COL[6].ROW[6].psum_out ),
    .row_en(row_en[6]),
    .rst(rst),
    .weight_in(\COL[6].ROW[5].wgt_out ),
    .weight_out(\COL[6].ROW[6].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[6].ROW[7].PE  (
    .activation_in(\COL[5].ROW[7].act_out ),
    .activation_out(\COL[6].ROW[7].act_out ),
    .clk(clk),
    .col_en(col_en[6]),
    .en(en),
    .partial_sum_in(\COL[5].ROW[7].psum_out ),
    .partial_sum_out(\COL[6].ROW[7].psum_out ),
    .row_en(row_en[7]),
    .rst(rst),
    .weight_in(\COL[6].ROW[6].wgt_out ),
    .weight_out(\COL[6].ROW[7].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[7].ROW[0].PE  (
    .activation_in(\COL[6].ROW[0].act_out ),
    .activation_out(\COL[7].ROW[0].act_out ),
    .clk(clk),
    .col_en(col_en[7]),
    .en(en),
    .partial_sum_in(\COL[6].ROW[0].psum_out ),
    .partial_sum_out(\COL[7].ROW[0].psum_out ),
    .row_en(row_en[0]),
    .rst(rst),
    .weight_in(weight_in_flat[63:56]),
    .weight_out(\COL[7].ROW[0].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[7].ROW[1].PE  (
    .activation_in(\COL[6].ROW[1].act_out ),
    .activation_out(\COL[7].ROW[1].act_out ),
    .clk(clk),
    .col_en(col_en[7]),
    .en(en),
    .partial_sum_in(\COL[6].ROW[1].psum_out ),
    .partial_sum_out(\COL[7].ROW[1].psum_out ),
    .row_en(row_en[1]),
    .rst(rst),
    .weight_in(\COL[7].ROW[0].wgt_out ),
    .weight_out(\COL[7].ROW[1].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[7].ROW[2].PE  (
    .activation_in(\COL[6].ROW[2].act_out ),
    .activation_out(\COL[7].ROW[2].act_out ),
    .clk(clk),
    .col_en(col_en[7]),
    .en(en),
    .partial_sum_in(\COL[6].ROW[2].psum_out ),
    .partial_sum_out(\COL[7].ROW[2].psum_out ),
    .row_en(row_en[2]),
    .rst(rst),
    .weight_in(\COL[7].ROW[1].wgt_out ),
    .weight_out(\COL[7].ROW[2].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[7].ROW[3].PE  (
    .activation_in(\COL[6].ROW[3].act_out ),
    .activation_out(\COL[7].ROW[3].act_out ),
    .clk(clk),
    .col_en(col_en[7]),
    .en(en),
    .partial_sum_in(\COL[6].ROW[3].psum_out ),
    .partial_sum_out(\COL[7].ROW[3].psum_out ),
    .row_en(row_en[3]),
    .rst(rst),
    .weight_in(\COL[7].ROW[2].wgt_out ),
    .weight_out(\COL[7].ROW[3].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[7].ROW[4].PE  (
    .activation_in(\COL[6].ROW[4].act_out ),
    .activation_out(\COL[7].ROW[4].act_out ),
    .clk(clk),
    .col_en(col_en[7]),
    .en(en),
    .partial_sum_in(\COL[6].ROW[4].psum_out ),
    .partial_sum_out(\COL[7].ROW[4].psum_out ),
    .row_en(row_en[4]),
    .rst(rst),
    .weight_in(\COL[7].ROW[3].wgt_out ),
    .weight_out(\COL[7].ROW[4].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[7].ROW[5].PE  (
    .activation_in(\COL[6].ROW[5].act_out ),
    .activation_out(\COL[7].ROW[5].act_out ),
    .clk(clk),
    .col_en(col_en[7]),
    .en(en),
    .partial_sum_in(\COL[6].ROW[5].psum_out ),
    .partial_sum_out(\COL[7].ROW[5].psum_out ),
    .row_en(row_en[5]),
    .rst(rst),
    .weight_in(\COL[7].ROW[4].wgt_out ),
    .weight_out(\COL[7].ROW[5].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[7].ROW[6].PE  (
    .activation_in(\COL[6].ROW[6].act_out ),
    .activation_out(\COL[7].ROW[6].act_out ),
    .clk(clk),
    .col_en(col_en[7]),
    .en(en),
    .partial_sum_in(\COL[6].ROW[6].psum_out ),
    .partial_sum_out(\COL[7].ROW[6].psum_out ),
    .row_en(row_en[6]),
    .rst(rst),
    .weight_in(\COL[7].ROW[5].wgt_out ),
    .weight_out(\COL[7].ROW[6].wgt_out )
  );
  (* src = "systolic_array.v:83.59-89.10" *)
  \$paramod$966773a7c3bc91e471672006b4d6600f62b050ab\mac_unit  \COL[7].ROW[7].PE  (
    .activation_in(\COL[6].ROW[7].act_out ),
    .activation_out(\COL[7].ROW[7].act_out ),
    .clk(clk),
    .col_en(col_en[7]),
    .en(en),
    .partial_sum_in(\COL[6].ROW[7].psum_out ),
    .partial_sum_out(\COL[7].ROW[7].psum_out ),
    .row_en(row_en[7]),
    .rst(rst),
    .weight_in(\COL[7].ROW[6].wgt_out ),
    .weight_out(\COL[7].ROW[7].wgt_out )
  );
  assign result_flat = { \COL[7].ROW[7].psum_out , \COL[6].ROW[7].psum_out , \COL[5].ROW[7].psum_out , \COL[4].ROW[7].psum_out , \COL[3].ROW[7].psum_out , \COL[2].ROW[7].psum_out , \COL[1].ROW[7].psum_out , \COL[0].ROW[7].psum_out , \COL[7].ROW[6].psum_out , \COL[6].ROW[6].psum_out , \COL[5].ROW[6].psum_out , \COL[4].ROW[6].psum_out , \COL[3].ROW[6].psum_out , \COL[2].ROW[6].psum_out , \COL[1].ROW[6].psum_out , \COL[0].ROW[6].psum_out , \COL[7].ROW[5].psum_out , \COL[6].ROW[5].psum_out , \COL[5].ROW[5].psum_out , \COL[4].ROW[5].psum_out , \COL[3].ROW[5].psum_out , \COL[2].ROW[5].psum_out , \COL[1].ROW[5].psum_out , \COL[0].ROW[5].psum_out , \COL[7].ROW[4].psum_out , \COL[6].ROW[4].psum_out , \COL[5].ROW[4].psum_out , \COL[4].ROW[4].psum_out , \COL[3].ROW[4].psum_out , \COL[2].ROW[4].psum_out , \COL[1].ROW[4].psum_out , \COL[0].ROW[4].psum_out , \COL[7].ROW[3].psum_out , \COL[6].ROW[3].psum_out , \COL[5].ROW[3].psum_out , \COL[4].ROW[3].psum_out , \COL[3].ROW[3].psum_out , \COL[2].ROW[3].psum_out , \COL[1].ROW[3].psum_out , \COL[0].ROW[3].psum_out , \COL[7].ROW[2].psum_out , \COL[6].ROW[2].psum_out , \COL[5].ROW[2].psum_out , \COL[4].ROW[2].psum_out , \COL[3].ROW[2].psum_out , \COL[2].ROW[2].psum_out , \COL[1].ROW[2].psum_out , \COL[0].ROW[2].psum_out , \COL[7].ROW[1].psum_out , \COL[6].ROW[1].psum_out , \COL[5].ROW[1].psum_out , \COL[4].ROW[1].psum_out , \COL[3].ROW[1].psum_out , \COL[2].ROW[1].psum_out , \COL[1].ROW[1].psum_out , \COL[0].ROW[1].psum_out , \COL[7].ROW[0].psum_out , \COL[6].ROW[0].psum_out , \COL[5].ROW[0].psum_out , \COL[4].ROW[0].psum_out , \COL[3].ROW[0].psum_out , \COL[2].ROW[0].psum_out , \COL[1].ROW[0].psum_out , \COL[0].ROW[0].psum_out  };
endmodule
